- ExtractMsg.py
just a little function to save the attachments. inspired by the fork from user @gabll.
> added save_attachments

- README.md
- extract_msg/__init__.py
- extract_msg/__main__.py
- extract_msg/base.py
- extract_msg/constants.py
- setup.py
- tests.py
Fix for next release being behind
> Next release

- CHANGELOG.md
- extract_msg/message.py
Fixed bug that somehow escaped detection that caused certain properties to not work.
Fixed bug with embedded msg files introduced in v0.24.0
> v0.24.2 (continued)

- .github/ISSUE_TEMPLATE/bug_report.md
- CHANGELOG.md
- README.rst
- extract_msg/__init__.py
- extract_msg/message.py
Fix for mattgwwalker#134 and other miscellaneous changes.
> Version 0.25.2

- README.rst
Updated the credits in the readme after asking how they wanted to be credited.
> Credits update

- .github/CONTRIBUTING
- .github/PULL_REQUEST_TEMPLATE.md
- CHANGELOG.md
- README.rst
- extract_msg/__init__.py
- extract_msg/utils.py
**v0.30.2**
* Fixed typo in `utils.knownMsgClass`.
* Updated contributing guidelines and pull request template. Pull requests were updated to match the new structure of the module while the guidelines were updated for clarity.
> Version 0.30.2

- extract_msg/message_base.py
Fixes a simple typo that causes an full exception to be raised when an HTML body is not present. Thanks for the work maintaining!
If you haven't completed the above items, please wait to create a PR until you have done so. We will try to review and reply to PRs as quickly as possible.
Once your PR is approved by a maintainer, we will either merge it into next-release or do a release with you or for you.
Thanks for contributing!
> fixes logger typo

- CHANGELOG.md
- README.rst
- extract_msg/__init__.py
- extract_msg/properties.py
- requirements.txt
**v0.30.9**
* Fixed the behavior of `Properties.get` so it actually behaves like a dict (that was the intent of it, but I did it the wrong way for some reason).
* Fixed a type that caused an exception when no HTML body could be found nor generated.
> Version 0.30.9

- README.rst
- extract_msg/utils.py
> Fix help message for --raw option

- CHANGELOG.md
- README.rst
- extract_msg/__init__.py
- extract_msg/message_base.py
- extract_msg/utils.py
**v0.30.11**
* [[TeamMsgExtractor #249](https://github.com/TeamMsgExtractor/msg-extractor/issues/249)] Fixed an error with opening the body causing the file to throw an uncaught exception in the `__init__` function of `MessageBase`. The error may still come up later, but you will still have general access to the instance.
* Fixed an issue with part of the command line documentation.
> Version 0.30.11

- CHANGELOG.md
- README.rst
- extract_msg/__init__.py
- extract_msg/msg.py
- setup.py
**v0.30.14**
* Fixed major bug in `MSGFile.listDir` that would cause it to give the wrong data due to caching. I forgot to have it cache a different result for each set of options, so it would always give the same result regardless of options after the first access.
* Minor updates to `setup.py`.
* Fixed URLs in `README`.
> Version 0.30.14

- CHANGELOG.md
- README.rst
- extract_msg/__init__.py
- extract_msg/signed_attachment.py
**v0.31.1**
* Updated signed attachment mimetype property from `mime` to `mimetype` to match with the regular attachment property.
> Version 0.31.1

- extract_msg/msg.py
- [ n/a ] Issue #: (Replace text with #<issue_number>)
- [ n/a ] Have you listed any changes to install or build dependencies?
- [ n/a ] Ensured your changes are compatible with Python 2.7 (ONLY FOR v0.29).
- [ n/a ] Have you updated the [CHANGELOG](CHANGELOG.md) with details of changes to the codebase, this includes new functionality, deprecated features, or any other material changes.
- [ n/a ] If necessary, have you bumped the version number? We will usually do this for you.
- [ n/a ] Have you included py.test tests with your pull request. (Not yet necessary)
- [ n/a ] Ensured your code is as close to PEP 8 compliant as possible?
- [ yes ] Ensured your pull request is to the `next-release` branch (or `v0.29` if applicable)?
The [last …
> Removed import for deleted MissingEncodingError exception

- README.rst
Fixed readme so pypi release works
> Attempt to fix readme

- CHANGELOG.md
- README.rst
- extract_msg/__init__.py
- extract_msg/message_base.py
**v0.35.3**
* [[TeamMsgExtractor #280](https://github.com/TeamMsgExtractor/msg-extractor/issues/280)] Fix typing issue in `message_base.py`.
> Version 0.35.3

- CHANGELOG.md
- README.rst
- extract_msg/__init__.py
- extract_msg/__main__.py
- extract_msg/attachment.py
- extract_msg/message_base.py
- extract_msg/msg.py
- extract_msg/utils.py
> Transfer updates to branch

- CHANGELOG.md
- README.rst
- extract_msg/__init__.py
- extract_msg/message_signed_base.py
- extract_msg/msg.py
Get code updates from next-release
> Merge new versions

- CHANGELOG.md
- README.rst
- extract_msg/__init__.py
- extract_msg/message_base.py
- extract_msg/message_signed_base.py
- extract_msg/msg.py
**v0.38.3**
* Fixed issues in HTML generation that caused line breaks to be omitted from large sections of the text.
* Fixed issues with requirements file.
> Version 0.38.3

- CHANGELOG.md
- README.rst
- extract_msg/__init__.py
- extract_msg/attachment.py
- extract_msg/constants.py
- extract_msg/contact.py
- extract_msg/message_base.py
- extract_msg/msg.py
- extract_msg/named.py
- extract_msg/ole_writer.py
- extract_msg/properties.py
- extract_msg/utils.py
Reverts TeamMsgExtractor/msg-extractor#328
> Revert "Update to next release"

- .gitignore
- docs/Makefile
- docs/conf.py
- docs/extract_msg.dev_classes.rst
- docs/extract_msg.rst
- docs/extract_msg.structures.rst
- docs/index.rst
- docs/make.bat
- docs/modules.rst
- readthedocs.yaml
> Added sphinx documentation 

- CHANGELOG.md
- extract_msg/__init__.py
- extract_msg/utils.py
- requirements.txt
If you haven't completed the above items, please wait to create a PR until you have done so. We will try to review and reply to PRs as quickly as possible.
Once your PR is approved by a maintainer, we will either merge it into next-release or do a release with you or for you.
Thanks for contributing!
> Update tzlocal and allow compressed_rtf and ebcdic updates

- CHANGELOG.md
- README.rst
- extract_msg/__init__.py
- extract_msg/attachments/attachment.py
- extract_msg/attachments/custom_att.py
- extract_msg/attachments/emb_msg_att.py
- extract_msg/constants/re.py
**v0.42.1**
* Fixed some constants being accessed with the wrong name (names were changed in reorganization).
* Removed unused regular expression.
> Fix issue with variable names

- CHANGELOG.md
- README.rst
- extract_msg/__init__.py
- extract_msg/msg_classes/message_base.py
- setup.cfg
**v0.48.2**
* Fixed bugs with `MessageBase.asEmailMessage()`. Numerous improvements to how it handles the data.
> Version 0.48.2

- CHANGELOG.md
- README.rst
- extract_msg/__init__.py
- extract_msg/attachments/attachment_base.py
- extract_msg/attachments/signed_att.py
**v0.48.3**
* [[TeamMsgExtractor #409](https://github.com/TeamMsgExtractor/msg-extractor/issues/409)] Added missing private method to `SignedAttachment`.
* Fixed some missing typing information.
> Version 0.48.3

- CHANGELOG.md
- README.rst
- extract_msg/__init__.py
- extract_msg/open_msg.py
**v0.48.7**
* [[TeamMsgExtractor #420](https://github.com/TeamMsgExtractor/msg-extractor/issues/420)] Fixed typo introduced in last version.
> Version 0.48.7

- CHANGELOG.md
- README.rst
- extract_msg/__init__.py
- extract_msg/msg_classes/message_base.py
**v0.50.1**
* [[TeamMsgExtractor #434](https://github.com/TeamMsgExtractor/msg-extractor/issues/434)] Fix bug introduced in previous version.
> Fix for #434
