ExtractMsg.py

The oliefileio package was renamed to olefile is 2014, and so the import should be updated.

OlefileIO is now named olefile

---

REQUIREMENTS
requirements.txt

Hey, neat project!
I've noticed that whether I'm using the py2 version at v0.20 or the newer py3 version at HEAD, they need `tzlocal` installed.
Not sure whether the intention is to use the REQUIREMENTS file or requirements.txt, so I've gone ahead and added it to both. Happy to change that.

Add tzlocal to requirements files

---

CHANGELOG.md
README.rst
extract_msg/__init__.py
extract_msg/message.py

**v0.26.2**
* Fixed error in `Message._registerNamedProperty` where I put the exception `KeyError` instead of `AttributeError`.

Version 0.26.2

---

CHANGELOG.md
README.rst
extract_msg/__init__.py
extract_msg/msg.py

**v0.27.4**
* [[mattgwwalker #152](https://github.com/mattgwwalker/msg-extractor/issues/152)] Fixed an issue where the name of an exception was put as the wrong thing.

v0.27.4 Fix for mattgwwalker#152

---

.gitignore
CHANGELOG.md
README.rst
extract_msg/__init__.py
extract_msg/constants.py
extract_msg/exceptions.py
extract_msg/utils.py
requirements.txt

**v0.27.5**
* Fixed an error in `utils.divide` that would cause it to drop the extra data is there was not enough to create a full division. For example, if you had a string that was 10 characters, and divided by 3, you would only receive a total of 9 characters back.
* Added some useful functions that will be used in the future.
* [[TeamMsgExtractor](https://github.com/TeamMsgExtractor/msg-extractor/issues/155)] Updated to use new version of tzlocal.
* Updated changelog to fit new repository.

Version 0.27.5

---

CHANGELOG.md
README.rst
extract_msg/__init__.py
extract_msg/constants.py
extract_msg/msg.py
extract_msg/utils.py

**v0.27.14**
* [[TeamMsgExtractor #173](https://github.com/TeamMsgExtractor/msg-extractor/issues/173)] Fixed typo that I made in the last version that broke things. I didn't have the resources to test this one myself, unfortunately.
* Fixed a typo in an exception message.

Version 0.27.14

---

.travis.yml
CHANGELOG.md
README.rst
extract_msg/__init__.py
extract_msg/__main__.py
extract_msg/appointment.py
extract_msg/attachment.py
extract_msg/attachment_base.py
extract_msg/compat/os_.py
extract_msg/constants.py
extract_msg/contact.py
extract_msg/data.py
extract_msg/dev.py
extract_msg/dev_classes/attachment.py
extract_msg/dev_classes/message.py
extract_msg/message.py
extract_msg/message_base.py
extract_msg/msg.py
extract_msg/named.py
extract_msg/prop.py
extract_msg/properties.py
extract_msg/recipient.py
extract_msg/utils.py

**v0.30.0**
* Removed all support for Python 2. This caused a lot of things to be moved around and changed from indirect references to direct references, so it's possible something fell through the cracks. I'm doing my best to test it, but let me know if you have an issue.
* Changed classes to now prefer super() over direct superclass initialization.
* Removed explicit object subclassing (it's implicit in Python 3 so we don't need it anymore).
* Converted most `.format`s into f strings.
* Improved consistency of docstrings. It's not perfect, but it should at least be better.
* Started the addition of type hints to functions and methods.
* Updated `utils.bytesToGuid` to make it faster and more efficient.
* Renamed `utils.msgEpoch` to `utils.filetimeToUtc` to be more descriptive.
* Updated …

Version 0.30.0

---

CHANGELOG.md
README.rst
extract_msg/__init__.py
extract_msg/__main__.py
extract_msg/attachment.py
extract_msg/data.py
extract_msg/message.py
extract_msg/message_base.py
extract_msg/utils.py
requirements.txt

**v0.30.1**
* [[TeamMsgExtractor #102](https://github.com/TeamMsgExtractor/msg-extractor/issues/102)] Added property `MessageBase.htmlBodyPrepared` which provides the HTML body that has been prepared for actual use or conversion to PDF. All attachments that can be injected into the body directly will be injected.
* Corrected a mistake in the documentation of `Message.save`.
* Fixed issue where the command line parser was not checking for raw in conjunction with other saving options.
* Changed `utils.setupLogging` to use `pathlib`.
* Improved reliability of the logic in `utils.setupLogging`.
* Removed function `utils.getContFileDir`.
* Cleaned up plain `Exception` being raised at the end of `utils.injectRtfHeader` if the injection failed. This now raises `RuntimeError`, an error that …

Version 0.30.1

---

CHANGELOG.md
README.rst
extract_msg/__init__.py
extract_msg/constants.py

**v0.30.3**
* [[TeamMsgExtractor #232](https://github.com/TeamMsgExtractor/msg-extractor/issues/232)] Updated list of known MSG class types so the module would correctly give `UnsupportedMSGTypeError` instead of `UnrecognizedMSGTypeError`.

Version 0.30.3

---

CHANGELOG.md
README.rst
extract_msg/__init__.py
extract_msg/message_base.py
requirements.txt

**v0.30.5**
* [[TeamMsgExtractor #225](https://github.com/TeamMsgExtractor/msg-extractor/issues/225)] Added the ability to generate the HTML body from the RTF body if it is encapsulated HTML. If there is no RTF body, then it will do a very basic generation from the plain text body. This process is automatically performed if the HTML body is missing.
* Added the ability for the plain text body to sometimes generate from the RTF body if the plain text body does not exist.
* Added documentation to `Message.save` for the `attachmentsOnly` option.

Version 0.30.5

---

CHANGELOG.md
README.rst
extract_msg/__init__.py
extract_msg/exceptions.py
extract_msg/message.py
extract_msg/message_base.py
extract_msg/msg.py
extract_msg/utils.py

**v0.30.7**
* [[TeamMsgExtractor #239](https://github.com/TeamMsgExtractor/msg-extractor/issues/239)] Fixed msg.py not having `import pathlib`.
* After going through the details of the example MSG files provided with the module, specifically unicode.msg, I now am glad I decided to put in some fail-safes in the HTML body processing. One of them does not have an `<html>`, `<head>`, nor `<body>` tag, and so would have had an error. This will actually prevent the header from injecting properly as well, so a bit of validation before was made necessary to ensure the HTML saving would still work.
* Added new exception `BadHtmlError`.
* Added new function `utils.validateHtml`.
* Updated README credits.
* Changed header logic to generate manually if the header data has been stripped (filled with …

v0.30.7 (ignore the name of the commit before, that was a typo lol)

---

CHANGELOG.md
README.rst
extract_msg/__init__.py
extract_msg/attachment.py

**v0.30.13**
* [[TeamMsgExtractor #257](https://github.com/TeamMsgExtractor/msg-extractor/issues/257)] Fixed missing documentation for `customPath` keyword argument to `Attachment.save`.

Version 0.30.13

---

CHANGELOG.md
README.rst
extract_msg/__init__.py
extract_msg/__main__.py
extract_msg/appointment.py
extract_msg/attachment.py
extract_msg/attachment_base.py
extract_msg/contact.py
extract_msg/data.py
extract_msg/dev.py
extract_msg/dev_classes/attachment.py
extract_msg/dev_classes/message.py
extract_msg/enums.py
extract_msg/message.py
extract_msg/message_base.py
extract_msg/message_signed.py
extract_msg/message_signed_base.py
extract_msg/msg.py
extract_msg/named.py
extract_msg/properties.py
extract_msg/recipient.py
extract_msg/signed_attachment.py
extract_msg/task.py
extract_msg/utils.py

**v0.33.0**
* [[TeamMsgExtractor #212](https://github.com/TeamMsgExtractor/msg-extractor/issues/212)] Added support for Task objects.
* Added additional parameter `overrideClass` to all `_ensureSetX` type functions. This parameter is a class to initialize using the data, if provided. The data will be provided as the first argument to the `__init__` function of the class *if* the data is not `None`. If the data is done, the value set and returned from `_ensureSetX` will be `None`. This can be overriden using the second added parameter, which defaults to this behavior. Simply set `preserveNone` to `False` to force the data to be passed to the class. Keep in mind that this means the class will receive `None` as it's first parameter.
* Updated `Named` class to make it more like the dictionary …

Version 0.33.0

---

CHANGELOG.md
README.rst
extract_msg/__init__.py
extract_msg/__main__.py
extract_msg/constants.py
extract_msg/exceptions.py
extract_msg/message.py
extract_msg/message_base.py
extract_msg/message_signed.py
extract_msg/msg.py
extract_msg/prop.py
extract_msg/recipient.py
extract_msg/utils.py
requirements.txt

**v0.34.0**
* [[TeamMsgExtractor #102](https://github.com/TeamMsgExtractor/msg-extractor/issues/102)] Added the option to directly save body to pdf. This requires that you either have wkhtmltopdf on your path or that you provide a path directly to it in order to work. Simply pass `pdf = True` to save to turn it on. More details in the doc for the save function. You can also do this from the command line using the `--pdf` option, incompatible with other body types.
* Added `--glob` option for allowing you to provide an msg path that will evaluate wildcards.
* Removed per-file output names as they weren't actually functional and currently add too much complexity. If anyone knows a way to handle it directly with `argparse` let me know.
* Added `chardet` as a requirement to help work around …

Version 0.34.0

---

CHANGELOG.md
README.rst
extract_msg/__init__.py
extract_msg/message_signed_base.py
extract_msg/signed_attachment.py
extract_msg/utils.py
requirements.txt

**0.34.2**
* [[TeamMsgExtractor #267](https://github.com/TeamMsgExtractor/msg-extractor/issues/267)] Fixed issue that caused signed messages that were .eml files to have their data field *not* be a bytes instance. This field will now *always* be bytes. If a problem making it bytes occurs, an exception will be raised to give you brief details.
* Added function `utils.unwrapMultipart` that takes a multipart message and acquires a plain text body, an HTML body, and a list of attachments from it. These attachments are returned as `dict`s that can easily be converted to `SignedAttachment`s. It replaces the logic `mailbits` was being used for, and as such `mailbits` is no longer required. The module may be reintroduced in the future.
* Added new property `emailMessage` to `SignedAttachment`, …

Version 0.34.2

---

CHANGELOG.md
README.rst
extract_msg/__init__.py
extract_msg/__main__.py
extract_msg/enums.py
extract_msg/exceptions.py
extract_msg/message_base.py
extract_msg/utils.py

**v0.34.3**
* Fixed issue that may have caused other olefile types to raise the wrong type of error when passed to `openMsg`.
* Fixed issues with changelog format.
* Fixed issue that caused progress to sometimes break the main loop when a file had Unicode characters if the console it was writing to didn't support them.
* Added option to `MessageBase` (and subsequently `openMsg`) that allows you to override the code being used for deencapsulation. See `MessageBase.__init__` for details on how to create an override function.

Version 0.34.3

---

CHANGELOG.md
README.rst
extract_msg/__init__.py
extract_msg/utils.py

**v0.35.2**
* Made a change to the argument handling for `--no-folders`. Since it requires `--attachmentsOnly` to work, I simply made it error when it's not given to avoid confusion.
* Updated README.
* Added `-v` to be used instead of `--verbose`. This allows you to do `-vvv` for verbosity level 3.

Version 0.35.2

---

CHANGELOG.md
README.rst
extract_msg/__init__.py
extract_msg/appointment.py
extract_msg/attachment.py
extract_msg/attachment_base.py
extract_msg/calendar.py
extract_msg/calendar_base.py
extract_msg/contact.py
extract_msg/dev_classes/message.py
extract_msg/enums.py
extract_msg/meeting_exception.py
extract_msg/meeting_forward.py
extract_msg/meeting_related.py
extract_msg/meeting_request.py
extract_msg/meeting_response.py
extract_msg/message_base.py
extract_msg/message_signed_base.py
extract_msg/msg.py
extract_msg/named.py
extract_msg/post.py
extract_msg/prop.py
extract_msg/properties.py
extract_msg/recipient.py
extract_msg/structures/entry_id.py
extract_msg/structures/report_tag.py
extract_msg/task.py
extract_msg/task_request.py
extract_msg/utils.py
extract_msg/validation.py

**v0.36.0**
* Improved type hints to tell when a function may not return anything.
* Added support for the `reportTag` property to `MessageBase`. I noticed this was one of the properties for `IPM.Outlook.Recall` so I decided to implement it. I'll work on ensuring all of `[MS-OXOMSG]` and `[MS-OXCMSG]` are implemented at a later date, including splitting off `REPORT` into it's own class, because it is it's own class.
* Fixed a few minor issues in some properties. Mostly some `bool` returning properties should have been returning False when they were not found instead of None. Ones that may return None are specifically typed as optional in the source code. Unfortunately using the `help` command doesn't seem to show the return type for properties for me at least on Python 3.9 and below.
* …

Version 0.36.0

---

CHANGELOG.md
README.rst
extract_msg/__init__.py
extract_msg/__main__.py
extract_msg/attachment.py
extract_msg/msg.py
extract_msg/prop.py
extract_msg/utils.py

**v0.36.1**
* [[TeamMsgExtractor #283](https://github.com/TeamMsgExtractor/msg-extractor/issues/283)] Added file for typing recognition.
* Added new option to allow messages with `NotImplementedError` attachments to at least save everything not related to them. From the command line this would be `--skip-not-implemented` or `--skip-ni`. From the save function, this would be the `skipNotImplemented` option.

Version 0.36.1

---

extract_msg/__main__.py
extract_msg/message_base.py
extract_msg/utils.py

I've seen that the `save()` function supports an undocumented `saveHeader` keyword argument and because I find it very useful (e.g. for analyzing the origin and other metadata of an email) I've added the command line argument `--save-header` to enable this option and added documentation to this argument.
As this function is already available, no additional install or build dependencies are needed.

Add --save-header argument to enable saving header

---

CHANGELOG.md
README.rst
extract_msg/__init__.py
extract_msg/__main__.py
extract_msg/message_base.py
extract_msg/utils.py

**v0.36.5**
* Documented and exposed to the command line the ability to save the headers to it's own file when saving the msg file. Thanks to martin-mueller-cemas on GitHub for fixing this (and telling me I can switch the branch a pull request points to). I don't know when I added the code to allow the user to do it, but somehow it was never documented and never exposed to the command line.

Version 0.36.5

---

CHANGELOG.md
README.rst
extract_msg/__init__.py
extract_msg/enums.py
extract_msg/msg.py
extract_msg/properties.py

**v0.37.0**
* [[TeamMsgExtractor #303](https://github.com/TeamMsgExtractor/msg-extractor/issues/303)] Renamed internal variable that wasn't changed when the other instances or it were renamed.
* [[TeamMsgExtractor #302](https://github.com/TeamMsgExtractor/msg-extractor/issues/302)] Fixed properties missing (a fatal MSG error) raising an unclear exception. It now uses `InvalidFileFormatError`.
* Updated `README` to contain documentation on command line option added in previous version.
* Removed `MSGFile.mainProperties` after deprecating it in v0.36.0.
* Added new `Properties` `Intelligence` type: `ERROR`. This type is used when a properties instance is created but has something wrong with it that is not necessarily fatal. Currently the only thing that will cause it is the properties …

Version 0.37.0

---

CHANGELOG.md
README.rst
extract_msg/__init__.py
extract_msg/__main__.py
extract_msg/attachment.py
extract_msg/message_base.py
extract_msg/msg.py
extract_msg/utils.py

**v0.37.1**
* Added option to save function (including `MSGFile.saveAttachments`) to skip any attachments marked as hidden. This can also be done from the command line with `--skip-hidden`.
* Fixed an issue that could cause an `MSGFile` to be included in the attachment names instead of just strings.
* Fixed up several comments.
* Fixed bug that would cause spaces at the end of the subject or filename to break the module.

Version 0.37.1

---

CHANGELOG.md
README.rst
extract_msg/__init__.py
extract_msg/__main__.py
extract_msg/attachment.py
extract_msg/attachment_base.py
extract_msg/constants.py
extract_msg/enums.py
extract_msg/msg.py
extract_msg/ole_writer.py
extract_msg/utils.py
requirements.txt
tests.py

**v0.38.0**
* [[TeamMsgExtractor #117](https://github.com/TeamMsgExtractor/msg-extractor/issues/117)] Added class `OleWriter` to allow the writing of OLE files, which allows for embedded MSG files to be extracted.
* Added function `MSGFile.export` which copies all streams and storages from an MSG file into a new file. This can "clone" an MSG file or be used for extracting an MSG file that is embedded inside of another.
* Added hidden function to `MSGFile` for getting the `OleDirectoryEntry` for a storage or stream. This is mainly for use by the `OleWriter` class.
* Added option `extractEmbedded` to `Attachment.save` (`--extract-embedded` on the command line) which causes embedded MSG files to be extracted instead of running their save methods.
* Fixed minor issues with …

Ole writer

---

extract_msg/contact.py

Fix cases where contact headers have missing values

---

extract_msg/enums.py
extract_msg/prop.py
extract_msg/utils.py

I found a file that is triggering this ValueError and believe those two lines related to the rawData had small typos. I took a look at that ErrorType and saw that it didn't exist (maybe renamed?) and assume that it meant to be ErrorCode. Lastly, I saw that x is not defined in that function of Enums and index makes sense. I can bring back the import of oletools if needed, but unless I'm missing something, it didn't look to be used in the class.
I am not certain it is necessary to have an issue created for such a small change, but would gladly create it if requested!
Thank you!

Small typos in Enums, Props and Utils.

---

CHANGELOG.md
README.rst
extract_msg/__init__.py
extract_msg/utils.py

**v0.41.1**
* [[TeamMsgExtractor #362](https://github.com/TeamMsgExtractor/msg-extractor/issues/362)] Fixed an issue with the removal of the `--dev` option missing one of the checks (I swear I actually tested it).

Version 0.41.1

---

CHANGELOG.md
README.rst
extract_msg/__init__.py
extract_msg/message_base.py
extract_msg/utils.py

**v0.41.3**
* [[TeamMsgExtractor #365](https://github.com/TeamMsgExtractor/msg-extractor/issues/365)] Fixed an issue that would cause certain values retrieved from the header to not be decoded properly. It does this when retrieving the values, so nothing about the header has been changed.
* Added new property `MessageBase.headerText` which is the text content of the header stream. Adjusted other things to use this instead of trying to retrieve the stream directly in multiple places.
* Added typing to `MessageBase.header`.

Fix for #365 (v0.41.3)

---

CHANGELOG.md
README.rst
extract_msg/__init__.py
extract_msg/message_base.py

**v0.41.5**
* Fixed an issue from version `0.41.3` where the header being present but missing the `From` field would cause an exception.

Version 0.41.5

---

CHANGELOG.md
README.rst
extract_msg/__init__.py
extract_msg/attachments/attachment_base.py

**v0.42.2**
* Fix bug in `AttachmentBase.mimetype` that would cause it to throw an error when accessed. This bug was introduced in `v0.42.0`.

Fix bug with mimetype

---

CHANGELOG.md
README.rst
extract_msg/__init__.py
extract_msg/msg_classes/message_base.py
temp-changelog.md

Added a function to `MessageBase` which allows the object to be converted to an `email.message.EmailMessage` instance, completely fulfilling #248 and at least partially fulfilling #56

Support for #56 / #248

---

CHANGELOG.md
README.rst
docs/conf.py
extract_msg/__init__.py
extract_msg/msg_classes/calendar_base.py
extract_msg/msg_classes/message_base.py
extract_msg/utils.py

**v0.44.0**
* Fixed a bug that caused `MessageBase.headerInit` to always return `False` after the 0.42.0 update.
* Changed `MessageBase.headerInit` to a property.
* Fixed `extract_msg.utils.__all__`.
* Minor regoanization within `extract_msg/utils.py`.
* Minor changes to docstrings.
* Minor README updates.
* Fix issue with folded header fields decoding incorrectly when given to `extract_msg.utils.decodeRfc2047`.

Version 0.44.0

---

CHANGELOG.md
README.rst
extract_msg/__init__.py
extract_msg/properties/prop.py

**v0.46.1**
* [[TeamMsgExtractor #394](https://github.com/TeamMsgExtractor/msg-extractor/issues/394)] Fix typo in props that caused the wrong number of bytes to be given to a struct.

Version 0.46.1: Fix #394

---

CHANGELOG.md
README.rst
extract_msg/__init__.py
extract_msg/constants/re.py

**v0.46.2**
* Adjusted typing information on regular expressions. They were using a subscript that was added in Python 3.9 (apparently that is something the type checker doesn't check for), which made the module incompatible with Python 3.8. If you are using Python 3.9 or higher a version check will switch to the more specific typing.

Version 0.46.2

---

CHANGELOG.md
README.rst
extract_msg/__init__.py
extract_msg/__main__.py
extract_msg/attachments/attachment_base.py
extract_msg/utils.py
extract_msg_tests/__init__.py
extract_msg_tests/cmd_line_tests.py
extract_msg_tests/ole_writer_tests.py

**v0.48.1**
* Added an option (`-s`, `--stdin`) to the command line to take an MSG file from stdin. This allows the user to pipe the MSG data from another program directly instead of having to write a middleman that uses the `extract-msg` library directly or having to write the file to the disk first.
* Changed main function to allow for manual argument list to be passed to it.
* Added attributes to `AttachmentBase` for creation and modification time. These can be accessed through `createdAt` or `creationTime` and `lastModificationTime` or `modifiedAt`.
* Changed `OleWriter` tests to output the name of the test file being done if an error occurs.
* Added tests for some command line stuff.

Version 0.48.1

---

CHANGELOG.md
README.rst
extract_msg/__init__.py
extract_msg/__main__.py

**v0.48.4**
* [[TeamMsgExtractor #411](https://github.com/TeamMsgExtractor/msg-extractor/issues/411)] Fix console script throwing error due to changed console args not defaulting.

Version 0.48.4

---

CHANGELOG.md
README.rst
extract_msg/__init__.py
extract_msg/open_msg.py

**v0.48.6**
* [[TeamMsgExtractor #417](https://github.com/TeamMsgExtractor/msg-extractor/issues/417)] Fixed issues with `openMsg` where some corrupted MSG files could end up throwing an uncaught exception and leaving the file handle open.

Version 0.48.6

---

CHANGELOG.md
README.rst
extract_msg/__init__.py
extract_msg/attachments/custom_att_handler/outlook_image_dib.py
extract_msg/attachments/custom_att_handler/outlook_image_meta.py
extract_msg/enums.py
extract_msg/open_msg.py
extract_msg/utils.py
extract_msg_tests/cmd_line_tests.py
extract_msg_tests/prop_tests.py

**v0.49.0**
* [[TeamMsgExtractor #427](https://github.com/TeamMsgExtractor/msg-extractor/issues/427)] Adjusted code for converting time stamps to create null dates for any time stamp beyond a certain point. The point was determined to be close to the existing null dates.
* [[TeamMsgExtractor #425](https://github.com/TeamMsgExtractor/msg-extractor/issues/425)] Added basic support for custom attachments that are Windows Metafiles.
* Changed tolerance of bitmap custom attachment handler to allow for attachments with only a CONTENT stream. This change was made after seeing an example of a file that only had a CONTENT stream and no other streams for the custom data. The code now also tries to create default values for things previously determined from those other streams.
* Fixed an issue in …

Version 0.49.0

---

CHANGELOG.md
extract_msg/open_msg.py

In this PR, I updated the library to recognize the class "IPM.SkypeTeams.Message" as a message type. I verified that this fixes the problem on 107 different MSG files with the class "IPM.SkypeTeams.Message". Closes #401.

Add support for MSG class type "IPM.SkypeTeams.Message"

---

CHANGELOG.md
README.rst
extract_msg/__init__.py
extract_msg/constants/__init__.py

**v0.51.1**
* Add class type added in last version to known class types.

Version 0.51.1

---

CHANGELOG.md
README.rst
extract_msg/__init__.py
extract_msg/msg_classes/message_base.py
extract_msg/msg_classes/msg.py
extract_msg/ole_writer.py

**v0.52.0**
* [[TeamMsgExtractor #444](https://github.com/TeamMsgExtractor/msg-extractor/issues/444)] Fix typo in string that prevented HTML body from generating from the plain text body properly.
* Adjusted the behavior of `MSGFile.areStringsUnicode` to prioritize the property specified by the parent MSG files for MSG files that are embedded. Additionally, added a fallback to rely on whether or not there is a stream using the `001F` type to determine the property value if it is entirely missing.
* Adjusted `OleWriter.fromMsg()` and `MSGFile.export()` to add the argument `allowBadEmbed` which helps to correct a few different issues that may appear in embedded MSG files. These corrections allow the extracte file to still be extracted and to open properly in Outlook.
* In addition to the …

Version 0.52.0

---

.github/workflows/python-package.yml
CHANGELOG.md
README.rst
extract_msg/__init__.py
extract_msg/exceptions.py
extract_msg/msg_classes/message_base.py
extract_msg/utils.py
extract_msg_tests/__init__.py
extract_msg_tests/util_tests.py
requirements.txt

**v0.53.1**
* Expanded allowable range for `red-black-tree-mod`.
* Fix issue with `MessageBase.asEmailMessage()` that prevented embedded MSG files from being attached.
* Expand allowable versions of `BeautifulSoup4`.

Version 0.53.1

---

CHANGELOG.md
README.rst
extract_msg/__init__.py
extract_msg/attachments/signed_att.py
extract_msg/msg_classes/message_base.py
extract_msg/msg_classes/task_request.py
extract_msg/structures/toc_entry.py
extract_msg/utils.py
extract_msg_tests/prop_tests.py

**v0.53.2**
* [[TeamMsgExtractor #452](https://github.com/TeamMsgExtractor/msg-extractor/issues/452)] Adjusted code to allow html encoding to be cached to try to speed up `bs4` operations.
* [[TeamMsgExtractor #453](https://github.com/TeamMsgExtractor/msg-extractor/issues/453)] Fixed handler for too large filetimes so that some filetimes being too large doesn't break the handler.
* Fixed a bug that would cause an error in task objects due to a lack of `enumerate`.
* Fix `TOCEntry` not initializing `DVTargetDevice` correctly.
* Add temporary properties for `ContentID` to `SignedAttachment`. AFAIK these can't ever be set, but this prevents errors in some places.

Version 0.53.2

---

CHANGELOG.md
README.rst
extract_msg/__init__.py
extract_msg/msg_classes/message_base.py

**v0.54.0**
* [[TeamMsgExtractor #456](https://github.com/TeamMsgExtractor/msg-extractor/issues/456)] Changed the prepared html output to use plainly encoded html instead of prettified, since prettifying will mangle the HTML output for some reason.

Version 0.54.0
